import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import vm from 'node:vm';

export function buildNames(items, data) {
  const names = [...new Set([
    ...Object.keys(data.mags), ...Object.keys(data.magCells), ...data.itemOrder,
  ])].sort();
  return Object.fromEntries(names.map((name) => {
    let entry = items[name];
    if (!entry) {
      const candidates = Object.entries(items)
        .filter(([key]) => key.toLowerCase() === name.toLowerCase());
      if (candidates.length !== 1) throw new Error(`Missing or ambiguous item identity: ${name}`);
      [, entry] = candidates[0];
    }
    if (typeof entry.zh !== 'string' || !entry.zh.trim()) {
      throw new Error(`Missing Chinese item name: ${name}`);
    }
    return [name, entry.zh];
  }));
}

async function main() {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const authority = process.env.DROPTABLE_I18N_AUTHORITY
    || path.join(root, '..', 'droptable', 'i18n_names.json');
  const source = await readFile(authority, 'utf8');
  const sandbox = { window: {} };
  vm.runInNewContext(await readFile(path.join(root, 'assets/js/mag-sim-data.js'), 'utf8'),
    sandbox, { timeout: 1000 });
  const names = buildNames(JSON.parse(source).items, sandbox.window.MAG_SIM);
  const digest = createHash('sha256').update(source).digest('hex');
  const content = `/* Generated by npm run sync:i18n from droptable/i18n_names.json (SHA-256 ${digest}).
 * Do not edit; English simulation identities remain unchanged. */
export const ITEM_NAMES = ${JSON.stringify(names, null, 2)};
`;
  const output = path.join(root, 'assets/js/items_i18n.js');
  if (process.argv.includes('--check')) {
    if (await readFile(output, 'utf8') !== content) {
      throw new Error('Item names are stale; run npm run sync:i18n');
    }
    console.log(`${Object.keys(names).length} item names match the authority.`);
  } else {
    await writeFile(output, content);
    console.log(`Generated ${Object.keys(names).length} authoritative item names.`);
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await main();
}
