import { createHash } from 'node:crypto';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repository = 'https://github.com/ephinea4haven/ephinea4haven.github.io';
const apiUrl = 'https://api.github.com/repos/ephinea4haven/ephinea4haven.github.io/commits/master';
const metadataFile = path.join(root, 'third_party', 'haven-mag-data', 'upstream.json');
const checkOnly = process.argv.includes('--check');
const files = [
  { path: 'assets/js/mag-evolution.js', global: 'window.MAG_EVOLUTION =' },
  { path: 'assets/js/mag-sim-data.js', global: 'window.MAG_SIM =' },
];

const sha256 = (content) => createHash('sha256').update(content).digest('hex');
const normalize = (content) => content.replace(/\r\n/g, '\n').trimEnd() + '\n';

async function download(url, options = {}) {
  const response = await fetch(url, {
    ...options,
    headers: {
      Accept: 'application/vnd.github+json',
      'User-Agent': 'magfeeder-data-sync',
      ...(process.env.GITHUB_TOKEN
        ? { Authorization: `Bearer ${process.env.GITHUB_TOKEN}` }
        : {}),
      ...options.headers,
    },
  });
  if (!response.ok) {
    throw new Error(`Unable to download ${url}: ${response.status} ${response.statusText}`);
  }
  return response.text();
}

function adaptSource(source, spec) {
  const normalized = normalize(source);
  if (!normalized.startsWith('/* Generated by scripts/build_mag_data.py')
      || !normalized.includes(spec.global)) {
    throw new Error(`${spec.path} no longer matches the canonical generated-data contract`);
  }
  const commentEnd = normalized.indexOf('*/\n');
  if (commentEnd < 0) {
    throw new Error(`${spec.path} is missing its generated-data header`);
  }
  return `/* Synced from ${repository}/blob/master/${spec.path}\n`
    + ' * Canonical generator: scripts/build_mag_data.py in the source repository.\n'
    + ' * Regenerate here: npm run sync:data\n'
    + ' * Do not edit by hand. */\n'
    + normalized.slice(commentEnd + 3);
}

async function writeAtomic(filename, content) {
  await mkdir(path.dirname(filename), { recursive: true });
  const temporary = `${filename}.${process.pid}.tmp`;
  await writeFile(temporary, content);
  await rename(temporary, filename);
}

async function verifyCurrent(filename, expected) {
  let actual;
  try {
    actual = await readFile(filename, 'utf8');
  } catch {
    throw new Error(`${path.relative(root, filename)} is missing; run npm run sync:data`);
  }
  if (actual !== expected) {
    throw new Error(`${path.relative(root, filename)} is stale; run npm run sync:data`);
  }
}

const commit = JSON.parse(await download(apiUrl));
if (!/^[0-9a-f]{40}$/.test(commit.sha || '')) {
  throw new Error('GitHub returned an invalid canonical-data commit SHA');
}

const sources = Object.fromEntries(files.map((spec) => [
  spec.path,
  `https://raw.githubusercontent.com/ephinea4haven/ephinea4haven.github.io/${commit.sha}/${spec.path}`,
]));
const sourceContents = await Promise.all(files.map((spec) => download(sources[spec.path])));
const generatedContents = sourceContents.map((source, index) => adaptSource(source, files[index]));
const metadata = `${JSON.stringify({
  repository,
  observedMasterCommit: commit.sha,
  sources,
  sourceSha256: Object.fromEntries(files.map((spec, index) => [
    spec.path,
    sha256(sourceContents[index]),
  ])),
  generatedSha256: Object.fromEntries(files.map((spec, index) => [
    spec.path,
    sha256(generatedContents[index]),
  ])),
}, null, 2)}\n`;

const outputs = [
  ...files.map((spec, index) => [path.join(root, spec.path), generatedContents[index]]),
  [metadataFile, metadata],
];

if (checkOnly) {
  let recorded;
  try {
    recorded = JSON.parse(await readFile(metadataFile, 'utf8'));
  } catch {
    throw new Error('third_party/haven-mag-data/upstream.json is missing or invalid; run npm run sync:data');
  }
  for (const [index, spec] of files.entries()) {
    if (sha256(sourceContents[index]) !== recorded.sourceSha256?.[spec.path]) {
      throw new Error(`${spec.path} is stale; run npm run sync:data`);
    }
    await verifyCurrent(path.join(root, spec.path), generatedContents[index]);
  }
  console.log(`Mag data snapshot is current (${recorded.observedMasterCommit.slice(0, 12)}).`);
} else {
  await Promise.all(outputs.map(([filename, content]) => writeAtomic(filename, content)));
  console.log(`Synced canonical Mag data (${commit.sha.slice(0, 12)}).`);
}
